# Generated by Django 4.2.5 on 2023-11-30 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logica.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naim', models.CharField(max_length=255, unique=True, verbose_name='Название рубрики')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор создания записи рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['naim'],
                'permissions': (('modify_rubrika', 'Can modify rubrika'),),
            },
        ),
        migrations.CreateModel(
            name='Utilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naim', models.CharField(max_length=255, unique=True, verbose_name='Название утилиты')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Описание утилиты')),
                ('file', models.FileField(blank=True, upload_to=logica.functions.get_timestamp_path_user, verbose_name='Файл утилиты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор загрузки утилиты')),
            ],
            options={
                'verbose_name': 'Утилита',
                'verbose_name_plural': 'Утилиты',
                'ordering': ['naim'],
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Statya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название статьи')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Описание статьи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('content', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Контент статьи')),
                ('kartinka', models.ImageField(blank=True, upload_to=logica.functions.get_timestamp_path_user, verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('rubrika', models.ManyToManyField(db_table='statya_rubrika', related_name='rubrika', to='logica.rubrika', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['title'],
                'permissions': (('modify_statya', 'Can modify statya'),),
            },
        ),
        migrations.CreateModel(
            name='Ocenka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('author_ocenka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avtor', to=settings.AUTH_USER_MODEL, verbose_name='Автор оценка')),
                ('komu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komu', to=settings.AUTH_USER_MODEL, verbose_name='Кому поставлена оценка')),
            ],
            options={
                'verbose_name': 'Оценки',
                'verbose_name_plural': 'Оценка',
                'ordering': ['-id'],
                'permissions': (('modify_ocenka', 'Can modify ocenka'),),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_description', models.TextField(default='', max_length=500, verbose_name='Описание комментируемой статьи')),
                ('txt', models.TextField(default='', max_length=500, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата публикации комментария')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('statya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.statya', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id'],
                'permissions': (('modify_comment', 'Can modify comment'),),
            },
        ),
    ]
