# Generated by Django 4.2.5 on 2023-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
        migrations.AddField(
            model_name='utilita',
            name='count_downloads',
            field=models.IntegerField(default=0, verbose_name='Счетчик скачиваний утилиты'),
        ),
    ]
