# Generated by Django 4.2.5 on 2023-12-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_statya_count_views_utilita_count_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statya',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Контент статьи'),
        ),
        migrations.AlterField(
            model_name='statya',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Описание статьи'),
        ),
    ]
