# Generated by Django 4.2.5 on 2023-12-02 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logica', '0003_alter_statya_content_alter_statya_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statya',
            name='author',
        ),
        migrations.AddField(
            model_name='statya',
            name='author',
            field=models.ManyToManyField(db_table='course_authors', related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
    ]
