# Generated by Django 4.2.5 on 2023-12-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0005_alter_statya_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statya',
            old_name='date',
            new_name='data_publication',
        ),
    ]
