# Generated by Django 4.2.5 on 2023-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0007_remove_statya_author_statya_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statya',
            name='rubrika',
            field=models.ManyToManyField(related_name='rubrika', to='logica.rubrika', verbose_name='Рубрика'),
        ),
    ]
