# Generated by Django 4.2.5 on 2023-12-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logica', '0008_alter_statya_rubrika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statya',
            name='rubrika',
            field=models.ManyToManyField(to='logica.rubrika'),
        ),
        migrations.CreateModel(
            name='Answer_to_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250, verbose_name='Текст ответа на комментарий')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.comment', verbose_name='Комментарий')),
                ('komu_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответы на комментарий',
            },
        ),
    ]
