# Generated by Django 4.2.5 on 2023-12-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0009_alter_statya_rubrika_answer_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rod_description',
        ),
    ]
