# Generated by Django 4.2.5 on 2023-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0012_answer_to_comment_author_otveta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации комментария'),
        ),
    ]
