# Generated by Django 4.2.5 on 2023-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0013_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statya',
            name='count_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
