# Generated by Django 4.2.5 on 2023-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0014_alter_statya_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='reiting',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
