# Generated by Django 4.2.5 on 2023-12-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0016_ocenka_statya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilita',
        ),
    ]
