# Generated by Django 4.2.5 on 2023-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0017_delete_utilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='statya',
            name='ban_author',
            field=models.BooleanField(default=False, verbose_name='Бан юзера'),
        ),
        migrations.AddField(
            model_name='statya',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено модератором'),
        ),
    ]
