# Generated by Django 4.2.5 on 2023-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilita',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Файл утилиты'),
        ),
    ]
