# Generated by Django 4.2.5 on 2023-12-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilites', '0002_utilita_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilita',
            name='ban_author',
            field=models.BooleanField(default=False, verbose_name='Бан юзера'),
        ),
    ]
